### ISSUE TITLE
TypeError:  method expected 2 arguments, got 3 with REUSE_DB

### ISSUE THREAD

**Issue by SoftwareMaven** [django-nose/django-nose#122]
Using MySQL 5.6.10, Django from source on stable/1.5.x, Python 3, South git tip, and the Python 3 django-nose branch.  Steps to reproduce are:

    $ REUSE_DB=1 ./manage.py test                                       
    nosetests --tests=uln,uln_ui --with-fixture-bundling --verbosity=1                                                                                        
    Creating test database for alias 'default'...
    ...................
    Ran 19 tests in 7.533s

    OK
    $ REUSE_DB=1 ./manage.py test                                       
    nosetests --tests=uln,uln_ui --with-fixture-bundling --verbosity=1                                                                                        
    TypeError: method expected 2 arguments, got 3

The TypeError traceback is:

    Traceback (most recent call last):
      File "/Users/travis/src/uln/dependencies/django/django/core/management/base.py", line 222, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/Users/travis/src/uln/dependencies/django/django/core/management/commands/test.py", line 72, in execute
        super(Command, self).execute(*args, **options)
      File "/Users/travis/src/uln/dependencies/django/django/core/management/base.py", line 255, in execute
        output = self.handle(*args, **options)
      File "/Users/travis/src/uln/dependencies/south/south/management/commands/test.py", line 8, in handle
        super(Command, self).handle(*args, **kwargs)
      File "/Users/travis/src/uln/dependencies/django/django/core/management/commands/test.py", line 89, in handle
        failures = test_runner.run_tests(test_labels)
      File "/Users/travis/src/uln/dependencies/django-nose/django_nose/runner.py", line 195, in run_tests
        result = self.run_suite(nose_argv)
      File "/Users/travis/src/uln/dependencies/django-nose/django_nose/runner.py", line 142, in run_suite
        addplugins=plugins_to_add)
      File "/Users/travis/src/uln/eggs/nose-1.3.0-py3.3.egg/nose/core.py", line 118, in __init__
        **extra_args)
      File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/unittest/main.py", line 125, in __init__
        self.runTests()
      File "/Users/travis/src/uln/eggs/nose-1.3.0-py3.3.egg/nose/core.py", line 197, in runTests
        result = self.testRunner.run(self.test)
      File "/Users/travis/src/uln/eggs/nose-1.3.0-py3.3.egg/nose/core.py", line 50, in run
        wrapper = self.config.plugins.prepareTest(test)
      File "/Users/travis/src/uln/eggs/nose-1.3.0-py3.3.egg/nose/plugins/manager.py", line 99, in __call__
        return self.call(*arg, **kw)
      File "/Users/travis/src/uln/eggs/nose-1.3.0-py3.3.egg/nose/plugins/manager.py", line 167, in simple
        result = meth(*arg, **kw)
      File "/Users/travis/src/uln/dependencies/django-nose/django_nose/plugin.py", line 75, in prepareTest
        self.old_names = self.runner.setup_databases()
      File "/Users/travis/src/uln/dependencies/django-nose/django_nose/runner.py", line 368, in setup_databases
        _skip_create_test_db, creation, creation.__class__)

**Comment by moss** [comment]
FWIW, I was having this issue with Python 3.4 and Django 1.7, and the fix above solved the problem entirely.
