### ISSUE TITLE
Running '$ ./manage.py test' yields optparse.OptionConflictError: option -p/--pattern: conflicting option string(s): -p

### ISSUE THREAD

**Issue by jesselathamdev** [django-nose/django-nose#123]
Hi there,

Wondering if I can get a hand with this if someone has some experience with basic configuration with django_nose and nose.  Seems that it might be something more than just me being a bonehead.

Attempting to run ./manage.py test and I receive the following error:
"optparse.OptionConflictError: option -p/--pattern: conflicting option string(s): -p"

Full traceback:
(portfolio16)[jesselatham portfolioapp-web]$ ./manage.py test
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jesselatham/.virtualenvs/portfolio16/src/django/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/jesselatham/.virtualenvs/portfolio16/src/django/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jesselatham/.virtualenvs/portfolio16/src/django/django/core/management/commands/test.py", line 51, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/jesselatham/.virtualenvs/portfolio16/src/django/django/core/management/base.py", line 236, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/Users/jesselatham/.virtualenvs/portfolio16/src/django/django/core/management/commands/test.py", line 60, in create_parser
    option_list=options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1219, in __init__
    add_help=add_help_option)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1261, in _populate_option_list
    self.add_options(option_list)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1039, in add_options
    self.add_option(option)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1020, in add_option
    self._check_conflict(option)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 995, in _check_conflict
    option)
optparse.OptionConflictError: option -p/--pattern: conflicting option string(s): -p

Notes:
installed using:
- instructions on website with TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
- also tried TEST_RUNNER = 'django_nose.BasicNoseRunner'
using:
- python 2.7.5 on Mac OSX
- Django development version (1.6.dev20130524184802)
- django-nose 1.1
- nose 1.3.0
have attempted:
- recreating clean virtualenv
- updating python from 2.7.3 -> 2.7.5
- removing any and all tests
- '$ nosetests' runs fine, but doesn't do any DB set up or teardown, clearly skips all the goodness of django_nose
- '$ ./manage.py help test' yields same error as reported

Here's my installed apps from BASE.py
INSTALLED_APPS = (
    # django core apps
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.humanize',

    # 3rd party addons
    'endless_pagination',
    'south',

    # portfolioapp specific
    'portfolioapp.apps.profiles',
    'portfolioapp.apps.portfolios',
    'portfolioapp.apps.markets',
    'portfolioapp.apps.cash',
    'portfolioapp.apps.core',
    'portfolioapp.apps.admin',
    'portfolioapp.apps.api',
)

installed apps from DEV.py (imports * from BASE.py)
INSTALLED_APPS += (
    # development tools
    'django_extensions',
    'debug_toolbar',
    'devserver',

    # testing tools
    'django_nose',
)

Let me know if you need anything else to help out.

Thanks,
Jess

**Comment by jwhitlock** [comment]
I believe this was fixed in v1.4.  Please try again, and re-open if it is still broken.
