### ISSUE TITLE
running ./manage.py test runs dist-package/nose/case.py

### ISSUE THREAD

**Issue by brianwu02** [django-nose/django-nose#171]
running ./manage.py test fails on these given tests. Does anyone know if this is because I am importing these tests somewhere and it is running them? Any explanations as to why these tests are running and/or failing would be helpful. thanks.
# 
## ERROR: Construct a test case with the specified label. Label should be of the

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 619, in newfunc
    return func(_arg, **kw)
TypeError: build_test() takes exactly 1 argument (0 given)
# 
## ERROR: Creates a test database, prompting the user for confirmation if the

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: create_test_db() takes at least 1 argument (0 given)

---

**Comment by brianwu02** [comment]
Hi, I don't know if this is information is still useful but it turns out we we running django_nose tests because we subclassed NoseTestSuiteRunner in our TestSuiteRunner

We had the following:
```from django_nose import NoseTestSuiteRunner

class TestSuiteRunner(NoseTestSuiteRunner):
    blah
 ```
Don't subclass and issue goes away.

**Comment by jwhitlock** [comment]
Smells similar to #209.
