### ISSUE TITLE
Tests are not starting to run after upgrading to django nose 1.4 on Django 1.8 and nose 1.3.6

### ISSUE THREAD

**Issue by aamirtharaj-rpx** [django-nose/django-nose#203]
Following is the exception I get on running 
`REUSE_DB=1 ./manage.py test -s`
```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 351, in create_parser
    self.add_arguments(parser)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in add_arguments
    test_runner_class.add_arguments(parser)
  File "/Users/antonyr/projects/office/pa_web/src/django-nose/django_nose/runner.py", line 250, in add_arguments
    value = cls._argparse_type[value]
KeyError: 'choice'
```

Thanks in advance for the help.

**Comment by valberg** [comment]
I've just encountered the exact same error
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/base.py", line 351, in create_parser
    self.add_arguments(parser)
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in add_arguments
    test_runner_class.add_arguments(parser)
  File "/Users/valberg/.virtualenvs/django18/lib/python2.7/site-packages/django_nose/runner.py", line 250, in add_arguments
    value = cls._argparse_type[value]
KeyError: 'choice'
```

**Comment by jwhitlock** [comment]
What happens if you leave out REUSE_DB=1 ?

**Comment by jwhitlock** [comment]
I'm working to get a matching environment, so I can replicate the error.

**Comment by jwhitlock** [comment]
The issue is that optparse's [choice type](https://docs.python.org/dev/library/optparse.html#standard-option-types) is not being converted to [argparse choices](https://docs.python.org/dev/library/argparse.html#choices).  It should be easy to do, but I can't replicate the bug.  **Is there a plugin or configuration setting that you are using that is adding a choice attribute?**

I have a fresh Django 1.8 project with django-nose installed to `INSTALLED_APPS` and `TEST_RUNNER`:
```sh
$ pip freeze
Django==1.8
django-nose==1.4
nose==1.3.6
wsgiref==0.1.2

$ ./manage.py diffsettings
BASE_DIR = '/Users/john/src/nose-test'  ###
DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': '/Users/john/src/nose-test/db.sqlite3', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': '', 'HOST': '', 'USER': '', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': '', 'OPTIONS': {}}}
DEBUG = True
INSTALLED_APPS = ('django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django_nose')
MIDDLEWARE_CLASSES = ('django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.auth.middleware.SessionAuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'django.middleware.security.SecurityMiddleware')
ROOT_URLCONF = 'nose_test_project.urls'  ###
SECRET_KEY = 'j3nco3hr83#$@pdzvmpif6$_i(d58s=&x9p!#67&-5rzc%zjg^'
SETTINGS_MODULE = 'nose_test_project.settings'  ###
STATIC_URL = '/static/'
TEMPLATES = [{'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
TIME_ZONE = 'UTC'
USE_L10N = True
USE_TZ = True
WSGI_APPLICATION = 'nose_test_project.wsgi.application'
```

**Comment by jwhitlock** [comment]
I've added a possible fix in https://github.com/jwhitlock/django-nose/tree/203_handle_choices_type, but I'm not sure if it works because I can't reproduce.  Can you test it?

```pip install --upgrade git+git://github.com/jwhitlock/django-nose@203_handle_choices_type#egg=django-nose```

**Comment by aamirtharaj-rpx** [comment]
@jwhitlock Thanks for your quick response. It looks nose-cover plugin I am using is the culprit. Give me couple of days for me to work on the piece once again. I'll keep you posted.

**Comment by aamirtharaj-rpx** [comment]
@jwhitlock Thanks John. It worked after I uninstalled nose-cov. There are other problems I am running into. I will specify them in a new issue in GitHub.

**Comment by mickm** [comment]
I just ran into this with nose-cov too. The fix @jwhitlock linked above worked for me with one small modification: `s/choices/choice/`

**Comment by jwhitlock** [comment]
@mickm thanks for the feedback.  I force-updated the 203_handle_choices_type branch. Does it look good?

**Comment by mickm** [comment]
@jwhitlock :thumbsup:
