### ISSUE TITLE
Crash with a recursion function usage

### ISSUE THREAD

**Issue by likeon** [django-nose/django-nose#209]
I have a function to walk through objects and convert all OrderedDict instances to dict instances.
```python
def get_testable_object(obj):
    if not isinstance(obj, (dict, list, OrderedDict)):
        return obj

    if isinstance(obj, list):
        return map(get_testable_object, obj)
    else:
        return {k: get_testable_object(v) for k, v in obj.iteritems()}
```

So my testcase crashes then the function is used:
```
./manage.py test --failfast api.tests.test_cart_payment
nosetests api.tests.test_cart_payment -x --verbosity=1
Creating test database for alias 'default'...
........E
======================================================================
ERROR: api.tests.test_cart_payment.get_testable_object
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/likeon/PP/action/beelinebackend/env/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/likeon/PP/action/beelinebackend/env/local/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
TypeError: get_testable_object() takes exactly 1 argument (0 given)

----------------------------------------------------------------------
Ran 9 tests in 2.721s

FAILED (errors=1)
Destroying test database for alias 'default'...

```

There is no error then it's runned with default django test runner.

Django==1.7.7
django-nose==1.3
nose==1.3.6

**Comment by jwhitlock** [comment]
Without more context, it would be impossible to determine what is going on.  Can you point to public code that demonstrates this bug?
