### ISSUE TITLE
SetUpClass error in FastFixtureTestCase:  'module' object has no attribute 'enter_transaction_management'

### ISSUE THREAD

**Issue by shanukus98765** [django-nose/django-nose#226]
I am using Django 1.8 with MySQL and the latest version of Django-nose pulled from this Github repo. I have used django_nose.FastFixtureTestCase instead of django.test.TestCase (as mentioned in the django-nose docs).

The test.py file in settings folder has this particular django-nose setting:
```
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
os.environ['REUSE_DB'] = "1"
```

My test_models.py (__init__.py contains Testcase imported from FastFixtureTestCase:
```
from django.db import connection
from django.test import Client

from ..models import TemplateUpload
from . import TestCase

class TemplateUploadTestCase(TestCase):

	fixtures = ['texparser_testdata']

	def setUp(self):
		self.client = Client()

	def test_correct_template_id(self):

		ieee_temp = TemplateUpload.objects.get(pk=1)
		acm_temp = TemplateUpload.objects.get(pk=2)
		self.assertEqual(ieee_temp.template_id, 1)
		self.assertEqual(acm_temp.template_id, 2)
		print('works:texparser/test_model/correct_template_id')
```
Error stack throwing up:
```
======================================================================
ERROR: test suite for <class 'texparser.tests.test_models.TemplateUploadTestCase'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shanu/.virtualenvs/typeset_dev/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/shanu/.virtualenvs/typeset_dev/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/shanu/.virtualenvs/typeset_dev/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/shanu/.virtualenvs/typeset_dev/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/shanu/typeset_revamped/typeset/libs/django_nose/testcases.py", line 50, in setUpClass
    transaction.enter_transaction_management(using=db)
AttributeError: 'module' object has no attribute 'enter_transaction_management'
```

**Comment by jwhitlock** [comment]
FastFixtureTestCase has not been maintained since at least Django 1.6, and there are [no tests](https://github.com/django-nose/django-nose/issues/220) to ensure it is working as intended.  This could be a small fix to sync with Django's evolving transaction support, or could be a complete rewrite.

**Comment by lokeshatbigbasket** [comment]
Is this issue fixed in django 1.11???

**Comment by jklemm** [comment]
@jwhitlock so, I guess that worth remove or rewrite the FastFixtureTestCase.  Keeping this class not working at the project don't make sense.

**Comment by jwhitlock** [comment]
@jklemm I'm sorry, I'm no longer using django-nose for my projects, and have moved on to pytest. I'm relying on the current users of the projects to come up with fixes and test each other's PRs.

I'm trying to collect PRs and issues related to this topic under https://github.com/django-nose/django-nose/milestone/5.
