### ISSUE TITLE
Migrations using call_command to install fixtures fail to be committed

### ISSUE THREAD

**Issue by thenrich** [django-nose/django-nose#231]
I have several data migrations that call `loaddata` using `call_command` which work as expected when running `./manage.py test` without django-nose. But, when I set `TEST_RUNNER` to `django_nose.NoseTestSuiteRunner` `./manage.py test` fails on my second data migration that inserts data with a foreign key.

After some debugging, I discovered that after the first data migration's `call_command` runs, the data is never inserted into the database, ultimately resulting in the failure of the next migration. Removing `TEST_RUNNER` and dropping into pdb after `call_command` shows the data added as expected.

This fixture data isn't even used in the tests, but running the migrations are part of my overall testing strategy for catching errors before the code is automatically deployed.

Am I missing something obvious?

**Comment by jwhitlock** [comment]
There is a bit of magic around migrations and fixtures, and the magic is broken - see https://github.com/django-nose/django-nose/milestones/Fix%20REUSE_DB=1 and https://github.com/django-nose/django-nose/milestones/Fix%20FastFixtureTestCase for examples.  It is possible that some of this code is changing the behavior of your migrations

**Comment by thenrich** [comment]
Gotcha -- I'll keep an eye on these.

**Comment by knabben** [comment]
Having the same issue (w/o REUSE_DB) with the call_command on setUpClass. I'm using MySQL, here the call trace:

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/code/project/src/django-bitfield/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/opt/code/project/src/django-bitfield/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/opt/code/project/src/django-bitfield/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/opt/code/project/src/django-bitfield/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/opt/code/project/lib/python2.7/site-packages/django/test/testcases.py", line 956, in setUpClass
    'database': db_name,
  File "/opt/code/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/opt/code/project/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 37, in new_execute
    return original_func(self, *args, **kwargs)
  File "/opt/code/project/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/opt/code/project/src/django-nose/django_nose/runner.py", line 389, in _foreign_key_ignoring_handle
    _old_handle(self, *fixture_labels, **options)
  File "/opt/code/project/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/opt/code/project/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 88, in loaddata
    with connection.constraint_checks_disabled():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/code/project/lib/python2.7/site-packages/django/db/backends/base/base.py", line 337, in constraint_checks_disabled
    disabled = self.disable_constraint_checking()
  File "/opt/code/project/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 308, in disable_constraint_checking
    self.cursor().execute('SET foreign_key_checks=0')
  File "/opt/code/project/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/opt/code/project/lib/python2.7/site-packages/django/db/backends/base/base.py", line 327, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
