### ISSUE TITLE
Unable to pass certain options to nosetests

### ISSUE THREAD

**Issue by pdrtrifork** [django-nose/django-nose#240]
Hi,

After upgrading our project to Django 1.8, we are no longer able to pass certain options to nosetests, e.g. --ignore-files and --exclude will cause an "AttributeError: 'tuple' object has no attribute 'append'"

Full trace:

    ./manage.py test --settings=mysite.settings.test --with-xunit --with-doctest --ignore-files="urls_hosted_.*\.py"
    Imported local_development_settings
    Traceback (most recent call last):
      File "./manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/pdr/Documents/Projects/Trifork/ThePerfectApp/venv-1.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
        utility.execute()
      File "/Users/pdr/Documents/Projects/Trifork/ThePerfectApp/venv-1.6/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/Users/pdr/Documents/Projects/Trifork/ThePerfectApp/venv-1.6/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
        super(Command, self).run_from_argv(argv)
      File "/Users/pdr/Documents/Projects/Trifork/ThePerfectApp/venv-1.6/lib/python2.7/site-packages/django/core/management/base.py", line 385, in run_from_argv
        options = parser.parse_args(argv[2:])
      File "/Users/pdr/Documents/Projects/Trifork/ThePerfectApp/venv-1.6/lib/python2.7/site-packages/django/core/management/base.py", line 64, in parse_args
        return super(CommandParser, self).parse_args(args, namespace)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1701, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1939, in _parse_known_args
        start_index = consume_optional(start_index)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1879, in consume_optional
        take_action(action, args, option_string)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1807, in take_action
        action(self, namespace, argument_values, option_string)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 930, in __call__
        items.append(values)
    AttributeError: 'tuple' object has no attribute 'append'

**Comment by jwhitlock** [comment]
I'm able to reproduce with ``./manage.py test --ignore-files="foo"``.  This appears to be a problem translating optparse's append action to argparse, and will affect other similar options like ``where``, ``doctestExtension``, and ``files``.
