### ISSUE TITLE
ImportError at startup django_nosebootstrap3

### ISSUE THREAD

**Issue by Kianoosh76** [django-nose/django-nose#271]
I installed django_nose and immediately faced this error when trying to run `manage.py` commands
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "//anaconda/envs/lyan/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "//anaconda/envs/lyan/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "//anaconda/envs/lyan/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "//anaconda/envs/lyan/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "//anaconda/envs/lyan/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "//anaconda/envs/lyan/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django_nosebootstrap3'
```

**Comment by Kianoosh76** [comment]
silly mistake!
In settings.py file I wrote:
```
REQUIRED_APPS = [
    'suit',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',
    'polymorphic_tree',
    'polymorphic',
    'mptt',
    'django_nose'
    'bootstrap3',
    '

```
I simply forgot a `,` between `django_nose` and `bootstrap3` so python thought that is a package with name `django_nostbootstrap3` :(

**Comment by jwhitlock** [comment]
I'm happy it is working now.
