### ISSUE TITLE
Error when adding `ipdb.set_trace()` inside tests

### ISSUE THREAD

**Issue by montaro** [django-nose/django-nose#274]
When I added;

```
import ipdb
ipdb.set_trace()
```

into a test case I get the following error:

```
(xyz-all)➜  xyz git:(xyz-61) ✗ ./manage.py test
nosetests --verbosity=1
Creating test database for alias 'default'...
...E..
======================================================================
ERROR: test_failing_get_or_create_group (zfsb_api.tests.aws.test_aws.TestAWSClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arefaey/workspace/cloud9ers/xyz/xyz/xyz_api/tests/aws/test_aws.py", line 111, in test_failing_get_or_create_group
    ipdb.set_trace()
  File "/Users/arefaey/venvs/xyz-all/lib/python3.5/site-packages/ipdb/__main__.py", line 93, in set_trace
    p = _init_pdb(context).set_trace(frame)
  File "/Users/arefaey/venvs/xyz-all/lib/python3.5/site-packages/ipdb/__main__.py", line 76, in _init_pdb
    p = Pdb(def_colors)
  File "/Users/arefaey/venvs/xyz-all/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 15, in __init__
    self.pt_init()
  File "/Users/arefaey/venvs/xyz-all/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 38, in pt_init
    self.pt_cli = CommandLineInterface(self._pt_app, eventloop=self.shell._eventloop)
AttributeError: 'TerminalInteractiveShell' object has no attribute '_eventloop'
```

I guess this is related. https://github.com/gotcha/ipdb/issues/105
The error happens when I use django-nose test runner and never happen when I use default django  test runner. Any clues?

**Comment by JBKahn** [comment]
it has to do with the way nose fiddles with stdout by default, in the linked thread we discuss the use of `nocapture` (with nose) which would circumvent the bug in ipdb.

**Comment by jwhitlock** [comment]
Agreed, ``./manage.py test -s`` or ``./manage.py test --ipdb`` might help

**Comment by jwhitlock** [comment]
No response in a month, assuming that helped.

**Comment by zsoobhan** [comment]
I know i'm a bit late to the party but using the `nose.tools` debugger also circumvents the stdout issues.
```python
from nose.tools import set_trace;set_trace()
```
