### ISSUE TITLE
ModuleNotFoundError: No module named 'django_nose' VENV

### ISSUE THREAD

**Issue by johnashu** [django-nose/django-nose#286]
Hi,

Everything runs perfectly outside of a VENV locally and in production

When I run Unit Testing via Jenkins all is also fine.

When I try to manage.py runserver inside of a VENV on my local machine I get the following traceback.
```

(eb-virt) PS E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\maffaz> python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001E697738268>
Traceback (most recent call last):
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 220, in wrapper
    fn(*args, **kwargs)
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 243, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 220, in wrapper
    fn(*args, **kwargs)
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_nose'
```

**Comment by jwhitlock** [comment]
It sounds like you need to install ``django-nose`` in your virtual environment, or you need to avoid using it if it is not installed. I use a pattern like this in ``settings.py``:

```
try:
    import django_nose
except ImportError:
    pass
else:
    assert django_nose  # Make pyflakes happy
    INSTALLED_APPS.append('django_nose')
    TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
```

**Comment by johnashu** [comment]
@jwhitlock 
Thanks for getting back to me..

I have nose installed:

(eb-virt) PS E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\Scripts> pip freeze
...
django-nose==1.4.5
django-rest-framework==0.1.0
djangorestframework==3.6.4
...

and the same VENV setup is used to push to production running the Nose tests along the way using Jenkins..

It will ONLY fail on my local machine inside VENV 

Check it out - I have added breaks so you can see the seperate commands

(eb-virt) PS E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\maffaz> python manage.py runserver

Unhandled exception in thread started by <function check_errors..wrapper at 0x000001E697738268>
Traceback (most recent call last):
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 220, in wrapper
fn(*args, **kwargs)
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
autoreload.raise_last_exception()
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 243, in raise_last_exception
raise exception0.with_traceback(exception[2])
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\utils\autoreload.py", line 220, in wrapper
fn(*args, **kwargs)
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django_init.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\apps\registry.py", line 89, in populate
app_config = AppConfig.create(entry)
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\site-packages\django\apps\config.py", line 90, in create
module = import_module(entry)
File "E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\eb-virt\lib\importlib_init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 978, in _gcd_import
File "", line 961, in _find_and_load
File "", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_nose'


(eb-virt) PS E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\maffaz> deactivate

PS E:\ITCIRCLECONSULT\GITHUB\maffaz-com\maffaz-com\maffaz> python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
September 01, 2017 - 16:47:13
Django version 1.11.4, using settings 'maffaz.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

**Comment by jwhitlock** [comment]
Do other commands work, like ``manage.py check``? What's the output of ``manage.py diffsettings``?

**Comment by johnashu** [comment]
ANY manage.py command returns the 

`ModuleNotFoundError: No module named 'django_nose'
`
Error

**Comment by jwhitlock** [comment]
I'm pretty sure this is not a django-nose issue, but instead with your environment. You should search for your errors, and look at some other other solutions, like https://stackoverflow.com/questions/43728431/modulenotfounderror-no-module-named-x

Is it possible that ``python`` is Python 2 in one environment and Python 3 in another? You may need to find and delete ``.pyc`` files and ``__pycache__`` folders.

**Comment by johnashu** [comment]
Hang on I just noticed something..
The last 3 lines omitted "<frozen importlib._bootstrap>" and pasted in "" instead

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked

**Comment by ianastewart** [comment]
Any progress on this? I am getting exactly the same error with django = 1.11.5, django-nose=1.4.5, nose=1.3.7

**Comment by johnashu** [comment]
Hey Ian,

I can't remember what I did but Im fairly certain it was something simple like creating a new Virtual ENV.. I also deleted the Caches .

**Comment by jwhitlock** [comment]
@johnashu glad to hear you got it working.  When I've had similar issues, it is due to mixing Python 2 and Python 3, or stale virtualenv, so I think rebuilding the virtualenv is a good thing to try.

**Comment by mateuspmello** [comment]
Just to add my scenario.
I`m used docker-compose, and some images had conflict. I cleanup every possible container, volumes and image and executed again and works fine!
