### ISSUE TITLE
Django 1.11 SetUpClass error in FastFixtureTestCase:  AttributeError: 'module' object has no attribute 'enter_transaction_management'

### ISSUE THREAD

**Issue by MidhunSukumaranBB** [django-nose/django-nose#289]
I am using django 1.11 and django-nose==1.4.5.  This is how my base test case class looks like:
`class BaseTestCase(FastFixtureTestCase):

    @classmethod
    def setUpClass(cls):
        from django.db import transaction
        for db in cls._databases():
            transaction.enter_transaction_management(using=db)
            transaction.managed(True, using=db)

        cls._fixture_setup()`

But getting SetUpClass error in FastFixtureTestCase:  AttributeError: 'module' object has no attribute 'enter_transaction_management'. I have seen similar issues [https://github.com/django-nose/django-nose/issues/226](url). Is it fixed?

**Comment by jwhitlock** [comment]
No, issue #226 is not fixed.  You could try the code in PR #258, which would give us some confirmation that the fix works.

**Comment by lokeshatbigbasket** [comment]
@jwhitlock @bennylope  I have gone through the code in [#258](https://github.com/django-nose/django-nose/pull/258/files) but, he is entirely removing for loop with transaction management. I am wondered how does this solves the problem. Don't we need transaction entirely for setting up `FastfixtureTestCase` ???

**Comment by vhlongmore** [comment]
I have tried the code in #258 and it gets me past the `AttributeError: 'module' object has no attribute 'enter_transaction_management'` issue. However, now all tests error with:
```
$ python ./manage.py test my.tests.test_module  --settings=test_settings --processes 2
nosetests my.tests.test_module --cover-erase --cover-package=utils,2 --processes 2 --verbosity=1
Creating test database for alias 'default'...
EEEEEEEEEE
======================================================================
ERROR: My test's doc string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/henrylongmore/.venv/myproject/lib/python2.7/site-packages/django/test/testcases.py", line 209, in __call__
    self._pre_setup()
  File "/Users/henrylongmore/.venv/myproject/lib/python2.7/site-packages/django_nose/testcases.py", line 123, in _pre_setup
    from django.contrib.sites.models import Site
  File "/Users/henrylongmore/.venv/myproject/lib/python2.7/site-packages/django/contrib/sites/models.py", line 84, in <module>
    class Site(models.Model):
  File "/Users/henrylongmore/.venv/myproject/lib/python2.7/site-packages/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
