### ISSUE TITLE
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by kausal-goibibo** [django-nose/django-nose#299]
I am on Django==2.0.4. When I add django-nose in INSTALLED_APPS, I get the below error. Please help.
django-nose==1.4.6
nose==1.3.7

# /usr/local/python3/bin/python3.6 manage.py help test
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/python3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.6/site-packages/django_nose/__init__.py", line 5, in <module>
    from django_nose.runner import BasicNoseRunner, NoseTestSuiteRunner
  File "/usr/local/python3/lib/python3.6/site-packages/django_nose/runner.py", line 285, in <module>
    class BaseRunner(DiscoverRunner):
  File "/usr/local/python3/lib/python3.6/site-packages/django_nose/runner.py", line 287, in BaseRunner
    options = _get_options()
  File "/usr/local/python3/lib/python3.6/site-packages/django_nose/runner.py", line 143, in _get_options
    django_opts = [opt.dest for opt in BaseCommand.option_list] + ['version']
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

**Comment by jwhitlock** [comment]
That code was removed in django-nose 1.4.4. Can you try re-installing django-nose 1.4.6?

These should both show ``(1, 4, 6)`` for the installed version:

```

/usr/local/python3/bin/python3.6 -c "import django_nose; print(django_nose.VERSION)"
/usr/local/python3/bin/python3.6 ./manage.py shell -c "import django_nose; print(django_nose.VERSION)"
```
