### ISSUE TITLE
Disk I/O error if using SQLite, and TEST_NAME is specified, and NAME=':memory:'

### ISSUE THREAD

**Issue by akaihola** [django-nose/django-nose#98]
This is an extra complication I noticed when analyzing issue #97. The scenario is a bit far-fetched – I doubt anyone needs this specific database configuration – but maybe this helps in solving #97.

To reproduce, install django-nose 7fd0132090256e752119f90a3d4568203c486f2e and create a new Django project with `django-admin.py startproject`. Do these changes to `settings.py`:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        'TEST_NAME': '/tmp/test.sqlite'
    }
}

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

INSTALLED_APPS = (
    # ...
    'django_nose',
    # ...
}
```

Run the tests:

```
$ ./manage.py test
nosetests --verbosity=1
Creating test database for alias 'default'...
Destroying old test database 'default'...
Type 'yes' if you would like to try deleting the test database '/tmp/test.sqlite', or 'no' to cancel: yes
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/commands/test.py", line 49, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "django_nose/runner.py", line 194, in run_tests
    result = self.run_suite(nose_argv)
  File "django_nose/runner.py", line 141, in run_suite
    addplugins=plugins_to_add)
  File "nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "nose/core.py", line 197, in runTests
    result = self.testRunner.run(self.test)
  File "nose/core.py", line 50, in run
    wrapper = self.config.plugins.prepareTest(test)
  File "nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "django_nose/plugin.py", line 75, in prepareTest
    self.old_names = self.runner.setup_databases()
  File "django_nose/runner.py", line 374, in setup_databases
    return super(NoseTestSuiteRunner, self).setup_databases()
  File "django/test/simple.py", line 317, in setup_databases
    self.verbosity, autoclobber=not self.interactive)
  File "django/db/backends/creation.py", line 262, in create_test_db
    self.connection.features.confirm()
  File "django/db/backends/__init__.py", line 418, in confirm
    self.supports_transactions = self._supports_transactions()
  File "django/db/backends/__init__.py", line 425, in _supports_transactions
    cursor.execute('CREATE TABLE ROLLBACK_TEST (X INT)')
  File "django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: disk I/O error
```

**Comment by jwhitlock** [comment]
Is this still an issue with django-nose 1.4 and a current Django?  Does the Django test cases have the same issue?
